---
- name: Setup environment for .ipynb automation # 설명용 이름
  hosts: localhost # 어디에 적용할 건지 (여기선 현재 서버) other: localhost, all 등
  become: yes # sudo 권한으로 실행할지 여부
  tasks: # 할 작업 목록 시작
    - name: Update apt cache
      apt: # apt install
        update_cache: yes

    # sudo apt update
    # sudo apt install -y python3-pip
    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    # sudo apt update
    # sudo apt install -y docker.io
    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Enable and start Docker service
      systemd: # 서비스 실행 systemctl start 같은것
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      user: # 유저 정보 설정 ex. usermod, groupadd 같은 것
        name: "{{ lockup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Install Ansible (via pip)
      pip:
        name: ansible

    # pip3 install jupyter nbconvert
    - name: Install Jupyter
      pip:
        name:
          - jupyter
          - nbconvert
